services:
  db:
    image: postgres:15
    container_name: postgres_talapker
    environment:
      POSTGRES_DB: talapker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d talapker" ]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
        db:
          condition: service_healthy